// Card definitions for King of Tokyo (2010 base set).
//
// type: 'keep'  -> stays in front of the monster for the rest of the game.
//       'discard' -> resolved immediately when bought, then discarded.
//
// Keep cards are implemented through hook keys consumed by engine.js.
// Discard cards carry an `effect` function run by the engine.

export const CARDS = [
  // ---------------------------------------------------------------- KEEP
  { id: 'acid_attack', name: 'Acid Attack', cost: 6, type: 'keep',
    text: 'Deal 1 extra damage each turn, even when you do not otherwise attack.' },
  { id: 'alien_metabolism', name: 'Alien Metabolism', cost: 3, type: 'keep',
    text: 'Buying cards costs you 1 less Energy.' },
  { id: 'alpha_monster', name: 'Alpha Monster', cost: 5, type: 'keep',
    text: 'Gain 1 Victory Point whenever you attack.' },
  { id: 'armor_plating', name: 'Armor Plating', cost: 4, type: 'keep',
    text: 'Ignore any damage of exactly 1.' },
  { id: 'background_dweller', name: 'Background Dweller', cost: 4, type: 'keep',
    text: 'You can always reroll any 3s you have, even after your last reroll.' },
  { id: 'burrowing', name: 'Burrowing', cost: 5, type: 'keep',
    text: 'Deal 1 extra damage while in Tokyo. Deal 1 damage to the monster taking over when you yield Tokyo.' },
  { id: 'camouflage', name: 'Camouflage', cost: 3, type: 'keep',
    text: 'When you take damage, roll a die for each point. Each Heart cancels one point of damage.' },
  { id: 'complete_destruction', name: 'Complete Destruction', cost: 3, type: 'keep',
    text: 'If you roll 1, 2, 3, Heart, Claw and Energy all at once, gain 9 Victory Points in addition to the normal results.' },
  { id: 'dedicated_news_team', name: 'Dedicated News Team', cost: 3, type: 'keep',
    text: 'Gain 1 Victory Point whenever you buy a card.' },
  { id: 'eater_of_the_dead', name: 'Eater of the Dead', cost: 4, type: 'keep',
    text: 'Gain 3 Victory Points every time a monster\'s Life goes to 0.' },
  { id: 'energy_hoarder', name: 'Energy Hoarder', cost: 3, type: 'keep',
    text: 'At the end of your turn gain 1 Victory Point for every 6 Energy you have.' },
  { id: 'even_bigger', name: 'Even Bigger!', cost: 4, type: 'keep',
    text: 'Your maximum Life is increased by 2. Gain 2 Life when you get this card.' },
  { id: 'extra_head_1', name: 'Extra Head', cost: 7, type: 'keep',
    text: 'You get 1 extra die.' },
  { id: 'extra_head_2', name: 'Extra Head', cost: 7, type: 'keep',
    text: 'You get 1 extra die.' },
  { id: 'fire_breathing', name: 'Fire Breathing', cost: 4, type: 'keep',
    text: 'Your neighbors (the players before and after you) take 1 extra damage when you deal damage.' },
  { id: 'freeze_time', name: 'Freeze Time', cost: 5, type: 'keep',
    text: 'On a turn where you score three 1s, take another turn with one less die.' },
  { id: 'friend_of_children', name: 'Friend of Children', cost: 3, type: 'keep',
    text: 'When you gain any Energy, gain 1 extra Energy.' },
  { id: 'giant_brain', name: 'Giant Brain', cost: 5, type: 'keep',
    text: 'You have one extra reroll each turn.' },
  { id: 'gourmet', name: 'Gourmet', cost: 4, type: 'keep',
    text: 'When scoring three 1s, gain 2 extra Victory Points.' },
  { id: 'herbivore', name: 'Herbivore', cost: 5, type: 'keep',
    text: 'Gain 1 Victory Point on your turn if you do not damage anyone.' },
  { id: 'herd_culler', name: 'Herd Culler', cost: 3, type: 'keep',
    text: 'Once each turn you can change one of your dice to a 1.' },
  { id: 'it_has_a_child', name: 'It Has a Child', cost: 7, type: 'keep',
    text: 'If you are eliminated, discard all your cards and Victory Points, heal to 10 Life and start again.' },
  { id: 'jets', name: 'Jets', cost: 5, type: 'keep',
    text: 'You suffer no damage when yielding Tokyo.' },
  { id: 'made_in_a_lab', name: 'Made in a Lab', cost: 2, type: 'keep',
    text: 'When buying cards you can also look at and buy the top card of the deck.' },
  { id: 'mimic', name: 'Mimic', cost: 8, type: 'keep',
    text: 'Copy a Keep card another monster has in play. You may move the Mimic counter to a different card at the start of your turn or while buying, for 1 Energy.' },
  { id: 'opportunist', name: 'Opportunist', cost: 3, type: 'keep',
    text: 'Whenever a new card is revealed in the shop, you may buy it immediately, even on another monster\'s turn.' },
  { id: 'parasitic_tentacles', name: 'Parasitic Tentacles', cost: 4, type: 'keep',
    text: 'During your buy step you can buy Keep cards from other monsters. You pay them the Energy.' },
  { id: 'psychic_probe', name: 'Psychic Probe', cost: 3, type: 'keep',
    text: 'Once per turn, force another monster to reroll one of its dice. If the reroll is a Heart, discard this card.' },
  { id: 'metamorph', name: 'Metamorph', cost: 3, type: 'keep',
    text: 'At the end of your turn you can sell any of your Keep cards back for the Energy you paid for them.' },
  { id: 'nova_breath', name: 'Nova Breath', cost: 7, type: 'keep',
    text: 'Your attacks damage all other monsters.' },
  { id: 'omnivore', name: 'Omnivore', cost: 4, type: 'keep',
    text: 'Once each turn you can score a 1, 2 and 3 for 2 Victory Points. Those dice still count for other combinations.' },
  { id: 'plot_twist', name: 'Plot Twist', cost: 3, type: 'keep',
    text: 'Change one die to any result. Discard this card after use.' },
  { id: 'poison_quills', name: 'Poison Quills', cost: 3, type: 'keep',
    text: 'When you score three 2s, also deal 2 damage.' },
  { id: 'poison_spit', name: 'Poison Spit', cost: 4, type: 'keep',
    text: 'When you deal damage to monsters, give them a Poison counter. A monster takes 1 damage per Poison counter at the end of its turn. A Heart removes a counter instead of healing.' },
  { id: 'rapid_healing', name: 'Rapid Healing', cost: 3, type: 'keep',
    text: 'During your turn, spend 2 Energy to heal 1 damage.' },
  { id: 'regeneration', name: 'Regeneration', cost: 4, type: 'keep',
    text: 'When you heal, heal 1 extra damage.' },
  { id: 'rooting_for_the_underdog', name: 'Rooting for the Underdog', cost: 3, type: 'keep',
    text: 'At the end of a turn where you have the fewest Victory Points, gain 1 Victory Point.' },
  { id: 'shrink_ray', name: 'Shrink Ray', cost: 6, type: 'keep',
    text: 'When you deal damage to monsters, give them a Shrink counter. A monster rolls one less die per Shrink counter. A Heart removes a counter instead of healing.' },
  { id: 'solar_powered', name: 'Solar Powered', cost: 2, type: 'keep',
    text: 'At the end of your turn gain 1 Energy if you have none.' },
  { id: 'spiked_tail', name: 'Spiked Tail', cost: 5, type: 'keep',
    text: 'When you attack, deal 1 extra damage.' },
  { id: 'stretchy', name: 'Stretchy', cost: 3, type: 'keep',
    text: 'Spend 2 Energy to change one of your dice to any result.' },
  { id: 'urbavore', name: 'Urbavore', cost: 4, type: 'keep',
    text: 'Gain 1 extra Victory Point when starting your turn in Tokyo. Deal 1 extra damage when dealing damage from Tokyo.' },
  { id: 'making_it_stronger', name: "We're Only Making It Stronger", cost: 3, type: 'keep',
    text: 'When you lose 2 or more Life at once, gain 1 Energy.' },
  { id: 'wings', name: 'Wings', cost: 6, type: 'keep',
    text: 'Whenever you would take damage, you may spend 2 Energy to take none.' },

  // ------------------------------------------------------------- DISCARD
  { id: 'apartment_building', name: 'Apartment Building', cost: 5, type: 'discard',
    text: 'Gain 3 Victory Points.',
    effect: (g, p) => g.gainVp(p, 3) },
  { id: 'commuter_train', name: 'Commuter Train', cost: 4, type: 'discard',
    text: 'Gain 2 Victory Points.',
    effect: (g, p) => g.gainVp(p, 2) },
  { id: 'corner_store', name: 'Corner Store', cost: 3, type: 'discard',
    text: 'Gain 1 Victory Point.',
    effect: (g, p) => g.gainVp(p, 1) },
  { id: 'skyscraper', name: 'Skyscraper', cost: 6, type: 'discard',
    text: 'Gain 4 Victory Points.',
    effect: (g, p) => g.gainVp(p, 4) },
  { id: 'drop_from_high_altitude', name: 'Drop From High Altitude', cost: 5, type: 'discard',
    text: 'Gain 2 Victory Points and take control of Tokyo City if you are not already in Tokyo.',
    effect: (g, p) => { g.gainVp(p, 2); g.seizeTokyoCity(p); } },
  { id: 'energize', name: 'Energize', cost: 8, type: 'discard',
    text: 'Gain 9 Energy.',
    effect: (g, p) => g.gainEnergy(p, 9) },
  { id: 'evacuation_orders', name: 'Evacuation Orders', cost: 7, type: 'discard',
    text: 'All other monsters lose 5 Victory Points.',
    effect: (g, p) => g.others(p).forEach(o => g.loseVp(o, 5)) },
  { id: 'flame_thrower', name: 'Flame Thrower', cost: 3, type: 'discard',
    text: 'All other monsters take 2 damage.',
    effect: (g, p) => g.damageAll(g.others(p).map(o => ({ p: o, n: 2 })), { source: p, attack: false }) },
  { id: 'frenzy', name: 'Frenzy', cost: 7, type: 'discard',
    text: 'Take another turn after this one.',
    effect: (g, p) => {
      if (g.turn.playerId !== p.id) { g.log(`Frenzy has no effect outside ${p.name}'s own turn.`); return; }
      g.turn.extraTurn = true; g.log(`${p.name} will take another turn (Frenzy).`);
    } },
  { id: 'gas_refinery', name: 'Gas Refinery', cost: 6, type: 'discard',
    text: 'Gain 2 Victory Points and deal 3 damage to all other monsters.',
    effect: (g, p) => { g.gainVp(p, 2); g.damageAll(g.others(p).map(o => ({ p: o, n: 3 })), { source: p, attack: false }); } },
  { id: 'heal', name: 'Heal', cost: 3, type: 'discard',
    text: 'Heal 2 damage.',
    effect: (g, p) => g.heal(p, 2, { card: true }) },
  { id: 'high_altitude_bombing', name: 'High Altitude Bombing', cost: 4, type: 'discard',
    text: 'All monsters, including you, take 3 damage.',
    effect: (g, p) => g.damageAll(g.alivePlayers().map(o => ({ p: o, n: 3 })), { source: p, attack: false }) },
  { id: 'jet_fighters', name: 'Jet Fighters', cost: 5, type: 'discard',
    text: 'Gain 5 Victory Points and take 4 damage.',
    effect: (g, p) => { g.gainVp(p, 5); g.enqueue(() => g.damage(p, 4, { source: p, attack: false })); } },
  { id: 'national_guard', name: 'National Guard', cost: 3, type: 'discard',
    text: 'Gain 2 Victory Points and take 2 damage.',
    effect: (g, p) => { g.gainVp(p, 2); g.enqueue(() => g.damage(p, 2, { source: p, attack: false })); } },
  { id: 'nuclear_power_plant', name: 'Nuclear Power Plant', cost: 6, type: 'discard',
    text: 'Gain 2 Victory Points and heal 3 damage.',
    effect: (g, p) => { g.gainVp(p, 2); g.heal(p, 3, { card: true }); } },
  { id: 'tanks', name: 'Tanks', cost: 4, type: 'discard',
    text: 'Gain 4 Victory Points and take 3 damage.',
    effect: (g, p) => { g.gainVp(p, 4); g.enqueue(() => g.damage(p, 3, { source: p, attack: false })); } },
  { id: 'vast_storm', name: 'Vast Storm', cost: 6, type: 'discard',
    text: 'Gain 2 Victory Points. All other monsters lose 1 Energy for every 2 Energy they have.',
    effect: (g, p) => { g.gainVp(p, 2); g.others(p).forEach(o => g.loseEnergy(o, Math.floor(o.energy / 2))); } },
];

export const CARD_BY_ID = Object.fromEntries(CARDS.map(c => [c.id, c]));

/** Public (serialisable) view of a card: no functions. */
export function cardView(id) {
  const c = CARD_BY_ID[id];
  if (!c) return null;
  return { id: c.id, name: c.name, cost: c.cost, type: c.type, text: c.text };
}
